### ISSUE TITLE
Lacks sound files for the numeric keypad and media keys

### ISSUE THREAD

**Issue by Poyeyo** [zevv/bucklespring#10]
I get lots of these errors while using the numeric keypad:

    Error opening audio file "./wav/90-1.wav": Failed to open file
    Error opening audio file "./wav/90-0.wav": Failed to open file
    Error opening audio file "./wav/ab-1.wav": Failed to open file
    Error opening audio file "./wav/ab-0.wav": Failed to open file
    Error opening audio file "./wav/a6-1.wav": Failed to open file
    Error opening audio file "./wav/a6-0.wav": Failed to open file
    Error opening audio file "./wav/a5-1.wav": Failed to open file
    Error opening audio file "./wav/a5-0.wav": Failed to open file

**Comment by francescortiz** [comment]
If you check the photo of the keyboard you will see that it doesn't have numeric keypad.

**Comment by zevv** [comment]
Yeah, kind of problematic for me to record these keys, since I don't have them. I could fake them by reusing the sounds of the other keys and panning those to the right, but that wouldn't be right, would it?

I see a few solutions here, both involve the help of others:

- someone records a complete sample set of all the keys on a full model M keyboard
- someone sends me a keyboard, and I'll provide the samples :)

**Comment by TjWallas** [comment]
@zevv For the short term, I would very welcome the idea of reusing some of the other keypress sounds for the numeric keypad keys :). You could even put that in a different branch than master for now.

It is a bit annoying when I am in the middle of an eargasm and then press a key on the numeric keypad ;)

**Comment by zevv** [comment]
I've added the `-f` command line option; this maps a default key sound to unknown keys. There's no location information added for unknown keys, so these are played from the middle of the stereo image.

This will have to do for now, until I can provide a sample set of a full keyboard.
