### ISSUE TITLE
Process[bucklespring] does not survive suspend/sleep/unreliable continuation

### ISSUE THREAD

**Issue by beyond9thousand** [zevv/bucklespring#107]
How do i make sure that the app survives suspends? I have tried adding it as a service but I get the following error each time I try to start/enable the service.

`Failed to connect to bus: No medium found`

Any suggestions are highly appreciated.

**Comment by zevv** [comment]
Hmm, this error does not originate from bucklespring itself, so likely it's openal, libinput or libudev complaining. I think we need some more info to debug this.
- I understand you have bucklesping running as a service, is that right?
- Did you compile from source, run from your distro's version, a snap, or otherwise?
- Can you try to isolate the problem: run bucklespring in the shell as a foreground application, then suspend and resume, and see what happens?

**Comment by beyond9thousand** [comment]
@zevv 
* No, it fails to run as a service.
* I installed it using pacman `community/bucklespring 1.5.1-1 [0B 5.36MiB] [Installed]`
* Ok, I will get back to you on this shortly

**Comment by BorjaRuizReverter** [comment]
I confirm that bucklespring does not wake up after system suspension. As @beyond9thousand said, the process remains sleep and does not seem to recover (I didnt expect hours to check if it does recover). 

However, we should blame pipeware for that. In fact, after
```bash
journalctl | grep buckle
``` 
my terminal returns this:

Dec 16 21:04:46 MyHostName **pipewire-pulse**[2437]: mod.protocol-pulse: client 0x555949667c20 [buckle]: **ERROR command**:-1 (invalid) tag:4294967295 error:25 (**Input/output error**)

**Comment by BorjaRuizReverter** [comment]
Just to complement my previous comment, I was using Bucklespring via Snap (on my fedora39). 

However, I have recently removed that installation and made a new one via Makefile, and everything works well!

So, now I confirm the opposite :sweat_smile:. Bucklespring does survive after system sleep!

P.S:
This installation via Makefile, however, yielded some errors, regarding these missing files (that the compilations does not find):
* libfluidsynth.so.1
* libdumb.so
* libFLAC.so.8

which seems not to affect the performance.
