### ISSUE TITLE
Feature Request: Static Volume Settings

### ISSUE THREAD

**Issue by Littlemac123** [zevv/bucklespring#123]
could there be a way to bypass the master volume of PipeWire/PulseAudio and stay at a set volume regardless what you want the system master audio to be set at. for example on a laptop where the prime way to change the volume is with the volume buttons on a keyboard changing the master volume of all apps, and keeping buckle spring always the same as clearly when you change that it was cause a video/music app was to quiet or to loud most of the time, not bucklespring.

**Comment by zevv** [comment]
Well, you already say it yourself: your volume settings change the master volume that affects all channels; afaik there is no way to exclude any specific channel from being excluded from the master controls, the master probably effects the hardware output level at the alsa driver level of your card, while the individual output channel controls are mixed  in software.

Not the answer you're looking for, but instead of controlling your master volume, try to adjust the individual output channels of the application which volume you want to adjust, and leave the master as it is.

Or, if you are *really* into the buckle sounds, get yourself a second soundcard and use this for the clickies exclusively :)
