### ISSUE TITLE
failed to create event tap

### ISSUE THREAD

**Issue by klassegeljakt** [zevv/bucklespring#31]
I get this when I run on Mac OSX Sierra:

```
sudo ./buckle
failed to create event tap
AL lib: (EE) alc_cleanup: 1 device not closed
```

What can be done?

**Comment by zevv** [comment]
* On 2016-11-01 09:50:23 +0100, Klazuz wrote:
 
> I get this when I run on Mac OSX Sierra:
> 
> ```
> sudo ./buckle
> failed to create event tap
> AL lib: (EE) alc_cleanup: 1 device not closed
> ```
> 
> What can be done?

I must admit I have no clue. The macos support was contributed by
Stephen Gelman, but due to lack of mac-ownership I have never even run
this code myself. I hope anyone with mac knowledge is reading this an
might help us out on this...

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by kimslawson** [comment]
@klassegeljakt check this issue: https://github.com/zevv/bucklespring/issues/15 It solved the problem for me.
