### ISSUE TITLE
Error loading libdumb.so and libfluidsynth.so.1 on start

### ISSUE THREAD

**Issue by blinry** [zevv/bucklespring#53]
This was brought to my attention by a user of the [bucklespring-git](https://aur.archlinux.org/packages/bucklespring-git/) AUR package. When dumb and fluidsynth are not installed, you're getting these warning when starting the program:

    Error loading libdumb.so: libdumb.so: cannot open shared object file: No such file or directory
    Error loading libfluidsynth.so.1: libfluidsynth.so.1: cannot open shared object file: No such file or directory

It works just as fine, anyhow. Can you think of why this happens?

**Comment by zevv** [comment]
Quoting Sebastian Morr (2017-06-16 10:04:15)
> This was brought to my attention by a user of the [bucklespring-git](https://aur.archlinux.org/packages/bucklespring-git/) AUR package. When dumb and fluidsynth are not installed, you're getting these warning when starting the program:
> 
>     Error loading libdumb.so: libdumb.so: cannot open shared object file: No such file or directory
>     Error loading libfluidsynth.so.1: libfluidsynth.so.1: cannot open shared object file: No such file or directory
> 
> It works just as fine, anyhow. Can you think of why this happens?

Bucklespring is a very simple OpenAL client app: we open the default
sound card and play a few samples, nothing fancy at all.

I'm afraid quite a number of bugs filed on Bucklespring are actually all
problems with OpenAL and the underlying sound configuration. There's a
hundred different Linux distro's on thousands of different hardware
combo's, all with their own quirks. I am far from an OpenAL expert,
since I have only ever used it in one project (this one), which 'Works
For Me™'.

I propose to take this issue (and a few others) and bring them under the
attention of the OpenAL developers, maybe they can help us out?

--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by zevv** [comment]
Because of a number of reported Bucklespring issues all seemed to be OpenAL related, I've asked help from the OpenAL-soft maintainer on Github, see

https://github.com/kcat/openal-soft/issues/127

It seems that your issue is caused by libalure, which for some reason tries to open a few libraries that do not exist.
