### ISSUE TITLE
bucklespring & trivial_opus_dec

### ISSUE THREAD

**Issue by zvezdochiot** [zevv/bucklespring#74]
There is a simple opus decoder:

https://github.com/deltabeard/trivial_opus_dec

Decodes the opus to raw.

Is there any way to combine it with libalure1 + libopenal1?

**Comment by deltabeard** [comment]
You could add an Opus decoder into bucklespring, but I don't think that would be a very great idea. Having the keypress samples in raw WAVE format means that there is less processing required to play the file.

By converting all of the samples to Opus, you would save file space, but the program would have to decode an Opus file on every keypress. Considering that file storage is cheap, and response time (especially for this application) is important, I wouldn't bother adding Opus support to bucklespring.

However, if you really wanted to add Opus support, I think you would read the Opus file around [here](https://github.com/zevv/bucklespring/blob/2357b69dc5e70e8b52f9d025b4ce682c71bf576e/main.c#L320), decode the file to raw wave samples, then point OpenAL to the decoded wave samples in RAM.

One thing I noticed in bucklespring is that "Wav files are loaded on demand". I would consider loading all the WAV files into RAM to reduce latency even further, since the WAV files aren't that large and some users still use slow hard disks.

Also, a minimal, cross-platform audio-streaming API is [sokol_audio.h](https://github.com/floooh/sokol#sokol_audioh). This could be used as a replacement to OpenAL to remove it as a dependency.

**Comment by Member1221** [comment]
Decoding ogg streams aren’t too expensive in my experience, so I’d say implementing simple ogg streams would be worth it. I can look in to implementing it later today.

**Comment by zvezdochiot** [comment]
See the trivial_opus_dec code. It is very simple. I did not find such a simple code for ogg. I was looking for.

**Comment by Member1221** [comment]
libvorbisfile is simple in itself, best to keep random dependencies down.

**Comment by zvezdochiot** [comment]
But there are no simple ogg decoders at hand.

**Comment by zvezdochiot** [comment]
Is there a "name" of these 6 lines?

**Comment by Member1221** [comment]
Audio can be compressed on disk and be decompressed on first play. Wouldn’t make too much overhead. Would decrease file size for people like me with a slow connection (can take upwards to 10 minutes to clone the repo on a bad day)

SDL2 mixer has its own issues, personally OpenAL is the best choice, especially when paired with oal-soft

**Comment by zvezdochiot** [comment]
It's not about the size of the disk, and in compactness for embedding in other systems.

**Comment by Member1221** [comment]
libvorbisfile is a part of the official xiph distribution though.

**Comment by deltabeard** [comment]
> Audio can be compressed on disk and be decompressed on first play. Wouldn’t make too much overhead.
> 
> SDL2 mixer has its own issues, personally OpenAL is the best choice, especially when paired with oal-soft

I'm only suggesting SDL2 as an alternative in case OpenAL does not work for some users. It may also resolve issues with use on Windows. It's good to have a variety I think.

> Would decrease file size for people like me with a slow connection (can take upwards to 10 minutes to clone the repo on a bad day, on a mobile connection)

Aren't clones compressed anyway? Surely you would only have to clone once too.

Could you all please quote, because I'm not sure to whom you're replying to.

Thanks.

**Comment by Member1221** [comment]
> I'm only suggesting SDL2 as an alternative in case OpenAL does not work for some users. It may also resolve issues with use on Windows. It's good to have a variety I think.
Windows provides its own official OpenAL implementation, one of the biggest issues rn seems to be the bitrate of the audio is very low. Can cause issues with playback. We should probably bump the bitrate to 41000 hz.

> Aren't clones compressed anyway? Surely you would only have to clone once too.
Yes,  but git clones are not optimized for audio so it does a p terrible job.

**Comment by Member1221** [comment]
> > It would also decrease installation size, which is always nice (even tho we have large drives mostly nowdays)
> 
> It would be nice to decrease the installation size. Have a look at libopusfile too (also from Xiph), as it produces better compression ratios than Vorbis.

I am more experienced with libvorbisfile, i've used it quite heavily in my engine. So if i'm to make anything i'd probably use that. also libvorbisfile only decodes.

For encoding ffmpeg is fine.

**Comment by zvezdochiot** [comment]
Just do not try to use libav.
Keep it simple.

**Comment by deltabeard** [comment]
> I am more experienced with libvorbisfile, i've used it quite heavily in my engine. So if i'm to make anything i'd probably use that. also libvorbisfile only decodes.

That's great, but using libopusfile is also very simple to use, and is better than vorbis. I have an example implementation at https://github.com/deltabeard/trivial_opus_dec/blob/master/trivial_opusdec.c and https://github.com/deltabeard/ctrmus/blob/master/source/opus.c if you change your mind.

Kind Regards,
Mahyar

**Comment by zvezdochiot** [comment]
The original wav should not have been removed.
You need to add .PHONY: ogg to the Makefile.

**Comment by Member1221** [comment]
Reason i removed wav was because my internet speed is too slow to do that, i'd recommend someone to add the wav files back in an secondary PR with a faster internet connection.

**Comment by Member1221** [comment]
@zevv should this be closed, since the ogg branch is there now?

**Comment by zevv** [comment]
Let's keep it open as a reminder; code in a branch can slowly die and rot and noone will ever care. I'm fine with merging this some day, but I'd like to hear some feedback from other OS users first.

**Comment by zvezdochiot** [comment]
no actual
