### ISSUE TITLE
Won't compile properly on Bash on Ubuntu on Windows 10

### ISSUE THREAD

**Issue by seagull** [zevv/bucklespring#9]
Since the win32 version doesn't work, I thought I'd try it on Windows 10's spiffy new bash shell, but after getting the packages:
-  libopenal-dev
- libalure-dev
- libxtst-dev
- make
- pkg-config
- gcc
- build-essential
- g++

I receive the following error:

Assertion 'pthread_mutex_unlock(&m->mutex) == 0' failed at pulsecore/mutex-posix.c:108, function pa_mutex_unlock(). Aborting.
Aborted (core dumped)

**Comment by zevv** [comment]
* On 2016-08-15 15:46:40 +0200, seagull wrote:
 
> Since the win32 version doesn't work, I thought I'd try it on Windows
> 10's spiffy new bash shell, 

Well, that's a pretty bold thing to do.

> Assertion 'pthread_mutex_unlock(&m->mutex) == 0' failed at
> pulsecore/mutex-posix.c:108, function pa_mutex_unlock(). Aborting.A
> Aborted (core dumped)

I have not experience running this environment yet, so no good advice on
how to help you here. My guess would be to find yourself a debugger
(does gdb work?) and see where the abort is coming from, but seeing that
it originates somewhere in a library (pulsecore/mutex-posix.c:108) I'm
not sure if the problem lies in the bucklespring code.

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by mirabilos** [comment]
Just drop pulseaudio…

**Comment by zevv** [comment]
Closing because I'm not planning to support this platform. If anybody feels like doing this, feel free of course :)
